# Generated by Django 5.2.4 on 2025-10-07 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomstore', '0005_passwordresetrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='N5sIJYgz8yC3Df1TI9WoGyLIOEsJRXlA', editable=False, max_length=32, unique=True),
        ),
    ]
