# Generated by Django 5.2.4 on 2025-10-07 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomstore', '0006_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='Fx3VI1lj9T6PzX63ARLChUMg0cu5yMRH', editable=False, max_length=32, unique=True),
        ),
    ]
